replicaCount: 1
environment: development
configFileName: config.yaml
configFilePath: /deploy/chart

config:
  service:
    sandbox: false
    tracingEnabled: false
  http:
    host: "0.0.0.0"
    port: 80
  metrics:
    name: datadog
    endpoint: ${DD_KUBERNETES_KUBELET_HOST}
    port: 8125
  tracing:
    name: datadog
    endpoint: ${DD_KUBERNETES_KUBELET_HOST}
    port: 8126

labels:
  app: shopify-plugin-frontend
  version: v0

host: shopify-plugin-frontend.development.getbread.com

aliasHosts: []

clusterIssuer: letsencrypt-staging

cacheHeader:
  Cache-Control: "public,max-age=604800,immutable"

doNotCacheHeader:
  Cache-Control: no-store

image:
  repository: 230377472753.dkr.ecr.us-east-1.amazonaws.com
  name: static_asset_service
  tag: master-latest

resources:
  requests:
    cpu: 1m
    memory: 4Mi
  limits:
    cpu: 100m
    memory: 400Mi
