apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopify-plugin-frontend
  namespace: {{ .Release.Namespace }}
  labels:
{{ .Values.labels | toYaml | indent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccountRoleARN | required "serviceAccountRoleARN is required" }}